DROP TABLE games;

CREATE TABLE IF NOT EXISTS games (
    id SERIAL PRIMARY KEY,
    game JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS rules (
    id INTEGER PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    elo INTEGER NOT NULL,
    description VARCHAR(120) NOT NULL
);