# Development dockerfile used in docker-compose, to speed speed up build times.
FROM rust:latest as builder

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY api ./api
COPY domain ./domain
COPY persistence ./persistence
COPY .sqlx ./.sqlx

RUN cargo build

FROM debian:bullseye-slim as runtime

WORKDIR /app

COPY --from=builder /app/target/release/api api
COPY client/dist client/dist

ENTRYPOINT ["./api"]