INSERT INTO rules (id, name, elo, description) VALUES
(0, 'None', 0, 'Good old normal chess.'),
(1, 'The people''s monarch', 750, 'You can only capture your opponent''s pawns with a pawn or king.'),
(2, 'Hungry hungry monarch', 1500, 'You can only capture your opponent''s pawns with your king.'),
(3, 'No jail can hold me', 2000, 'Your opponents pawns can not be captured.'),
(4, 'Figurehead', 750, 'Your king can''t actually capture anything.'),
(10, 'Can''t Convert Her', 250, 'Your bishops can''t capture the opponent''s queen.'),
(17, 'Animosity', 1250, 'Your pawns can only capture other pawns.'),
(12, 'Punching Down', 750, 'Your queen can only capture pawns.'),
(9, 'Can''t Stomp Her', 250, 'Your knights can''t capture the opponent''s queen.'),
(8, 'Two Guys In A Cheap Costume', 500, 'Your knights can''t actually capture anything.'),
(7, 'False Prophets', 500, 'Your bishops can''t actually capture anything.'),
(5, 'Trophy Wife', 750, 'Your queen can''t actually capture anything.'),
(15, 'Anti-Theist', 750, 'Your queen can only capture bishops.'),
(6, 'Fool Of A Rook', 750, 'Your rooks can''t actually capture anything.'),
(16, 'Pawn v. Pawn', 1000, 'You can only capture your opponent''s pawns with your pawns.'),
(13, 'Demolition Woman', 750, 'Your queen can only capture rooks.'),
(18, 'Lepers', 1500, 'Your pawns cannot capture other pawns.'),
(20, 'Sacred', 1000, 'You can''t capture bishops.'),
(21, 'No Animals Were Harmed In The Playing Of This Chess Game', 1000, 'You can''t capture knights.'),
(14, 'Heiress To The Elmer''s Fortune', 750, 'Your queen can only capture knights.'),
(11, 'Can''t Imprison Her', 250, 'Your rooks can''t capture the opponent''s queen.'),
(19, 'Stonework Enjoyer', 1000, 'You can''t capture rooks.'),
(28, 'Long Service', 250, 'Your bishops can''t move after turn 20.'),
(24, 'Poisoned Apple', 1000, 'Your queen can''t move after turn 6.'),
(22, 'Before The Clock Strikes 12', 500, 'Your queen can''t move after turn 12.'),
(30, 'Quick Prayer', 750, 'Your bishops can''t move after turn 10.'),
(32, 'Sleep Tight', 500, 'Your knights can''t move after turn 15.'),
(26, 'Not To Code', 750, 'Your rooks can''t move after turn 20.'),
(25, 'Wrong Permits', 500, 'Your rooks can''t move after turn 25.'),
(23, 'Sleeping Beauty', 750, 'Your queen can''t move after turn 9.'),
(33, 'Don''t Let The Bedbugs Bite', 750, 'Your knights can''t move after turn 10.'),
(27, 'Condemnable', 1000, 'Your rooks can''t move after turn 15.'),
(29, 'A Sermon Or Two', 500, 'Your bishops can''t move after turn 15.'),
(31, 'Good Night', 250, 'Your knights can''t move after turn 20.'),
(34, 'Border Guards', 750, 'Your rooks can only move along the a and h files and the 1st and 8th rank.'),
(37, 'The Queen of Darkness', 750, 'Your queen can only move to dark squares.'),
(35, 'The King of Darkness', 750, 'Your king can only move to dark squares.'),
(36, 'The King of Light', 750, 'Your king can only move to light squares.'),
(38, 'The Queen of Light', 750, 'Your queen can only move to light squares.'),
(41, 'E-zy', 750, 'You can''t land any chess piece on the e file.'),
(43, 'No ec-cess', 1000, 'You can''t land any chess piece on the c or e files.'),
(45, 'What the hec', 1500, 'You can''t land any chess piece on the h, e, or c files.'),
(40, 'Age restriction', 750, 'You can''t land any chess piece on the h file.'),
(39, 'I can''t C', 750, 'You can''t land any chess piece on the c file.'),
(44, 'Ch. 0', 1000, 'You can''t land any chess piece on the c or h files.'),
(42, 'eh...', 1000, 'You can''t land any chess piece on the e or h files.'),
(51, 'Rush A', 250, 'Open with a4, a5 or a5, a4.'),
(53, 'You''re Going To University And That''s Final!', 500, 'You are forced to play the Scholar''s Mate: e4, Bc4, Qh5 or e5, Bc5, Qh4.'),
(56, 'Tempt Fate', 500, 'Open with f3, g4 or f6, g5 and hope for the best.'),
(54, 'Anti-Feingold', 500, 'Open with f3, f4 or f6, f5.'),
(49, 'Outsiders', 250, 'Open with a4, h4 or a5, h5.'),
(46, 'Good Game', 250, 'Start with g3, g4 or g6, g5.'),
(58, 'Bongcloud And Back', 750, 'Open with e4, Ke2, Ke1 / e5, Ke7, Ke8.'),
(50, 'Say Cheese!', 250, 'Open with c4, d3, e4 or c5, d6, e5.'),
(59, 'The Knights Grimm', 250, 'Open with Na3, Nh3 or Na6, Nh6.'),
(47, 'Ctrl-Z', 250, 'Open with Nc3, Nb1 or Nc6, Nb8.'),
(55, 'Guns Out', 500, 'Open with a4, Ra3, h4, Rh3 or a5, Ra6, h5, Rh6.'),
(57, 'Bongcloud', 500, 'Open with e4, Ke2 or e5, Ke7.'),
(52, 'Rush B', 250, 'Open with b4, b5 or b5, b4.'),
(48, 'Gates Are Open, Come On In', 250, 'Open with d3, f3 or d6, f6.');