[package]
name = "migrations"
version = "0.1.0"
edition = "2024"

[dependencies]
persistence = { path = "../persistence" }
anyhow = "1.0.97"
serde_json = "1.0.140"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
tokio = "1.43.0"
