[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
axum = { version = "0.7.5", features = ["ws"] }
axum-server = "0.6.0"
serde = { version = "1.0.203"}
domain = { path = "../domain" }
persistence = { path = "../persistence" }
tower-sessions = "0.12.2"
tower-http = { version = "0.5.2", features = ["fs"] }
socketioxide = { version="0.14.0", features=["state"] }
tracing = "0.1.40"
env_logger = "0.11.5"
config = "0.14.0"
async-timers = "0.1.4"
moka = { version = "0.12.10", features = ["future"] }
futures = "0.3.31"
futures-util = "0.3.31"
